version: "3"

services:
  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:  
      - fcc5bf92de4ca247ead2f1f4:/var/lib/mysql
      - 11aa82eebc21ea5e1d52914c:/var/run/mysqld
      - ./dbaccess.cnf:/dbaccess.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: password
  
volumes:
  # database data
  fcc5bf92de4ca247ead2f1f4:
  # database socket
  11aa82eebc21ea5e1d52914c:
